const products = [
  {
    id: "1",
    title: "Apples x lb",
    title1: null,
    price: 2.1,
    offerPrice: null,
    stock: 12,
    img: "apples.jpg",
    additionalImages: ["apples-side-view.jpg", "apples-sliced.jpg", "apples-in-basket.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "0001",
    title: "Albendazol",
    title1: null,
    price: 330,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/albendazol.png",
    additionalImages: [
      "Farmacia/Antimicrobianos/albendazol-caja.png",
      "Farmacia/Antimicrobianos/albendazol-prospecto.png",
      "Farmacia/Antimicrobianos/albendazol-tabletas.png",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: true,
  },
  {
    id: "9",
    title: "Azitromicina",
    title1: null,
    price: 490,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/AZITROMICINA-500MG-CAJA-POR-3-TABLETAS-INCLINADO.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/AZITROMICINA-500MG-CAJA-FRONTAL.jpg",
      "Farmacia/Antimicrobianos/AZITROMICINA-500MG-TABLETAS.jpg",
      "Farmacia/Antimicrobianos/AZITROMICINA-500MG-PROSPECTO.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "2",
    title: "Amoxicilina",
    title1: null,
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/amoxicilina.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/amoxicilina-caja.jpg",
      "Farmacia/Antimicrobianos/amoxicilina-capsulas.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "77",
    title: "Amoxicilina en Suspensión",
    title1: null,
    price: 650,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/amoxicilina suspención.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/amoxicilina-suspension-frasco.jpg",
      "Farmacia/Antimicrobianos/amoxicilina-suspension-medida.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "3",
    title: "Ciprofloxacino 500mg",
    title1: null,
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/CIPROFLOXACINO-500-MG.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/CIPROFLOXACINO-BLISTER.jpg",
      "Farmacia/Antimicrobianos/CIPROFLOXACINO-CAJA-LATERAL.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "4",
    title: "Cefalexina",
    title1: null,
    price: 490,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/Cefalexina.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/Cefalexina-blister.jpg",
      "Farmacia/Antimicrobianos/Cefalexina-caja-abierta.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "888",
    title: "Cefalexina Suspensión",
    title1: null,
    price: 750,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/cefalexina suspension.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/cefalexina-suspension-frasco-abierto.jpg",
      "Farmacia/Antimicrobianos/cefalexina-suspension-dosificador.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "5",
    title: "Berry es feugiat mollis",
    title1: null,
    price: 2.3,
    offerPrice: null,
    stock: 12,
    img: "berry.jpg",
    additionalImages: ["berry-closeup.jpg", "berry-bowl.jpg", "berry-dessert.jpg"],
    category: "Electrodomésticos",
    subcategory: "Refrigeración",
    allowBankTransfer: true,
  },
  {
    id: "6",
    title: "berry feugiat dui non mollis",
    title1: null,
    price: 2.22,
    offerPrice: null,
    stock: 12,
    img: "berry2.jpg",
    additionalImages: ["berry2-basket.jpg", "berry2-pile.jpg"],
    category: "Electrodomésticos",
    subcategory: "Refrigeración",
    allowBankTransfer: true,
  },
  {
    id: "7",
    title: "Doxiciclina",
    title1: null,
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/doxiciclina.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/doxiciclina-blister.jpg",
      "Farmacia/Antimicrobianos/doxiciclina-caja-lateral.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "789",
    title: "Diclofenaco + Paracetamol",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/Diclofenaco + Paracetamol.jpg",
    additionalImages: [
      "Farmacia/Antiinflamatorios/Diclofenaco-Paracetamol-blister.jpg",
      "Farmacia/Antiinflamatorios/Diclofenaco-Paracetamol-prospecto.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antiinflamatorios",
    allowBankTransfer: false,
  },
  {
    id: "00012",
    title: "Fluconazol",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/Fluconazol.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/Fluconazol-capsula.jpg",
      "Farmacia/Antimicrobianos/Fluconazol-caja-abierta.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "000",
    title: "Ibuprofeno",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/ibuprofeno.jpg",
    additionalImages: [
      "Farmacia/Antiinflamatorios/ibuprofeno-blister.jpg",
      "Farmacia/Antiinflamatorios/ibuprofeno-tableta.jpg",
      "Farmacia/Antiinflamatorios/ibuprofeno-prospecto.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antiinflamatorios",
    allowBankTransfer: false,
  },
  {
    id: "000222",
    title: "Mebendazol",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/mebendazol.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/mebendazol-caja-abierta.jpg",
      "Farmacia/Antimicrobianos/mebendazol-tabletas.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "6698",
    title: "Metronidazol 500mg",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/METRONIDAZOL-500MG.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/METRONIDAZOL-BLISTER.jpg",
      "Farmacia/Antimicrobianos/METRONIDAZOL-TABLETA.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "66",
    title: "Paracetamol",
    title1: null,
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/paracetamol.jpg",
    additionalImages: [
      "Farmacia/Antiinflamatorios/paracetamol-blister.jpg",
      "Farmacia/Antiinflamatorios/paracetamol-caja-abierta.jpg",
      "Farmacia/Antiinflamatorios/paracetamol-tableta.jpg",
    ],
    category: "Farmacia",
    subcategory: "Analgésicos",
    allowBankTransfer: false,
  },
  {
    id: "87665",
    title: "Sulfaprim",
    title1: null,
    price: 310,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/sulfaprim.jpg",
    additionalImages: [
      "Farmacia/Antimicrobianos/sulfaprim-blister.jpg",
      "Farmacia/Antimicrobianos/sulfaprim-caja-lateral.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "8",
    title: "Sulfaprim (Jarabe)",
    title1: null,
    price: 900,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/Sulfaprim Suspension.jpg",
    additionalImages: [
      "Farmacia/Antiinflamatorios/Sulfaprim-Suspension-frasco-abierto.jpg",
      "Farmacia/Antiinflamatorios/Sulfaprim-Suspension-dosificador.jpg",
    ],
    category: "Farmacia",
    subcategory: "Antimicrobianos",
    allowBankTransfer: false,
  },
  {
    id: "11",
    title: "cherry feugiat dui non mollis",
    title1: null,
    price: 7.88,
    offerPrice: 6.88,
    stock: 12,
    img: "cherry.jpg",
    additionalImages: ["cherry-bowl.jpg", "cherry-closeup.jpg", "cherry-tree.jpg"],
    category: "Electrodomésticos",
    subcategory: "Refrigeración",
    allowBankTransfer: true,
  },
  {
    id: "22",
    title: "chicken feugiat dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "chicken.jpg",
    additionalImages: ["chicken-cooked.jpg", "chicken-raw-pieces.jpg", "chicken-package.jpg"],
    category: "meat",
    subcategory: "Arroz",
    allowBankTransfer: true,
  },
  {
    id: "33",
    title: "Arroz Blanco RAINHA (1 kg / 2.2 lb)",
    title1:"Precio por Kilogramo" ,
    price: 700,
    offerPrice: null,
    stock: 30,
    img: "Pastas, granos y cereales/Arroz/e6qSIHlA_400x400.jpg",
    additionalImages: ["Pastas, granos y cereales/Arroz/e6qSIHlA_400x400 (2).jpg", "Pastas, granos y cereales/Arroz/e6qSIHlA_400x400-1.jpg"],
    category: "meat",
    subcategory: "Arroz",
    allowBankTransfer: true,
  },
  {
    id: "44",
    title: "clemen feugiat dui",
    title1: null,
    price: 4.99,
    offerPrice: null,
    stock: 12,
    img: "clemen.jpg",
    additionalImages: ["clemen-peeled.jpg", "clemen-basket.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "55",
    title: "cod feugiat dui non",
    title1: null,
    price: 9.88,
    offerPrice: null,
    stock: 12,
    img: "cod.jpg",
    additionalImages: ["cod-fillet.jpg", "cod-cooked.jpg", "cod-package.jpg"],
    category: "meat",
    subcategory: "Fish",
    allowBankTransfer: true,
  },
  {
    id: "88",
    title: "dates feugiat non duilis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "dates.jpg",
    additionalImages: ["dates-bowl.jpg", "dates-package.jpg", "dates-closeup.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "99",
    title: "fresh fish feugiat dui",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish.jpg",
    additionalImages: ["fish-fillet.jpg", "fish-whole.jpg", "fish-cooked.jpg"],
    category: "meat",
    subcategory: "Fish",
    allowBankTransfer: true,
  },
  {
    id: "00",
    title: "fish lorem ipsum",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish2.jpg",
    additionalImages: ["fish2-closeup.jpg", "fish2-fillet.jpg"],
    category: "meat",
    subcategory: "Fish",
    allowBankTransfer: true,
  },
  {
    id: "111",
    title: "fish non mollis feugiat dui",
    title1: null,
    price: 4.88,
    offerPrice: 3.25,
    stock: 12,
    img: "fish3.jpg",
    additionalImages: ["fish3-package.jpg", "fish3-cooked.jpg"],
    category: "meat",
    subcategory: "Fish",
    allowBankTransfer: true,
  },
  {
    id: "222",
    title: "lemon non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lemon.jpg",
    additionalImages: ["lemon-sliced.jpg", "lemon-basket.jpg", "lemon-juice.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "333",
    title: "Aliquam lime dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lime.jpg",
    additionalImages: ["lime-sliced.jpg", "lime-basket.jpg", "lime-juice.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "444",
    title: "Aliquam mango dui non",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mango.jpg",
    additionalImages: ["mango-sliced.jpg", "mango-whole.jpg", "mango-ripe.jpg"],
    category: "Electrodomésticos",
    subcategory: "Cocina",
    allowBankTransfer: true,
  },
  {
    id: "555",
    title: "Aliquam meat dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat.jpg",
    additionalImages: ["meat-raw.jpg", "meat-cooked.jpg", "meat-package.jpg"],
    category: "meat",
    subcategory: "Beef",
    allowBankTransfer: true,
  },
  {
    id: "666",
    title: "meat feugiat dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: 4.0,
    stock: 12,
    img: "meat2.jpg",
    additionalImages: ["meat2-raw.jpg", "meat2-cooked.jpg", "meat2-sliced.jpg"],
    category: "meat",
    subcategory: "Beef",
    allowBankTransfer: true,
  },
  {
    id: "777",
    title: "Aliquam feugiat dui non meat",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat3.jpg",
    additionalImages: ["meat3-raw.jpg", "meat3-cooked.jpg", "meat3-package.jpg"],
    category: "meat",
    subcategory: "Beef",
    allowBankTransfer: true,
  },
  {
    id: "999",
    title: "pears feugiat dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "pears.jpg",
    additionalImages: ["pears-sliced.jpg", "pears-basket.jpg", "pears-ripe.jpg"],
    category: "Electrodomésticos",
    subcategory: "Refrigeración",
    allowBankTransfer: true,
  },
  {
    id: "1111",
    title: "Aliquam salmon dui non mollis",
    title1: null,
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "salmon.jpg",
    additionalImages: ["salmon-fillet.jpg", "salmon-cooked.jpg", "salmon-smoked.jpg"],
    category: "meat",
    subcategory: "Fish",
    allowBankTransfer: true,
  },
  {
    id: "bread1",
    title: "Sprouts Classic Seedsational Bread 14 oz",
    title1: null,
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread.jpg",
    additionalImages: ["bread-sliced.jpg", "bread-whole.jpg", "bread-toasted.jpg"],
    category: "bakery",
    subcategory: "Bread",
    allowBankTransfer: true,
  },
  {
    id: "bread2",
    title: "Traditional Corn Special Bread",
    title1: null,
    price: 1.75,
    offerPrice: null,
    stock: 12,
    img: "bread2.jpg",
    additionalImages: ["bread2-sliced.jpg", "bread2-whole.jpg", "bread2-package.jpg"],
    category: "bakery",
    subcategory: "Bread",
    allowBankTransfer: true,
  },
  {
    id: "bread3",
    title: "Sprouts Classic Seedsational Bread",
    title1: null,
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread3.jpg",
    additionalImages: ["bread3-sliced.jpg", "bread3-whole.jpg", "bread3-closeup.jpg"],
    category: "bakery",
    subcategory: "Bread",
    allowBankTransfer: true,
  },
  {
    id: "toast",
    title: "Oven Baked Garlic & Cheese Toast",
    title1: null,
    price: 1.7,
    offerPrice: null,
    stock: 12,
    img: "toast.jpg",
    additionalImages: ["toast-package.jpg", "toast-cooked.jpg", "toast-closeup.jpg"],
    category: "bakery",
    subcategory: "Toast",
    allowBankTransfer: true,
  },
  {
    id: "toast2",
    title: "Oven Baked Italian Herb with Olive Oil Toast",
    title1: null,
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "toast2.jpg",
    additionalImages: ["toast2-package.jpg", "toast2-cooked.jpg", "toast2-closeup.jpg"],
    category: "bakery",
    subcategory: "Toast",
    allowBankTransfer: true,
  },
  {
    id: "cookies",
    title: "Raspberry Crumble Cookies",
    title1: null,
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "cookies.jpg",
    additionalImages: ["cookies-package.jpg", "cookies-closeup.jpg", "cookies-stack.jpg"],
    category: "bakery",
    subcategory: "Cookies",
    allowBankTransfer: true,
  },
  {
    id: "cookies2",
    title: "Chocolate Chip Cookies",
    title1: null,
    price: 3.0,
    offerPrice: null,
    stock: 12,
    img: "cookies2.jpg",
    additionalImages: ["cookies2-package.jpg", "cookies2-stack.jpg", "cookies2-closeup.jpg"],
    category: "bakery",
    subcategory: "Cookies",
    allowBankTransfer: true,
  },
  {
    id: "cookies3",
    title: "Freshly Baked Chocolate Chip Cookie",
    title1: null,
    price: 2.5,
    offerPrice: null,
    stock: 12,
    img: "cookies3.jpg",
    additionalImages: ["cookies3-package.jpg", "cookies3-stack.jpg", "cookies3-broken.jpg"],
    category: "bakery",
    subcategory: "Cookies",
    allowBankTransfer: true,
  },
  {
    id: "muffin0",
    title: "Cake",
    title1: null,
    price: 12000,
    offerPrice: null,
    stock: 12,
    img: "Panadería y Dulcería/IMG-20250511-WA0006.jpg",
    additionalImages: [
      "Panadería y Dulcería/IMG-20250508-WA0020.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0020.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0020.jpg",
    ],
    category: "bakery",
    subcategory: "Muffin",
    allowBankTransfer: true,
  },
  {
    id: "muffin",
    title: "Thomas Cinnamon Raisin English Muffins",
    title1: null,
    price: 4000,
    offerPrice: null,
    stock: 12,
    img: "Panadería y Dulcería/IMG-20250508-WA0019.jpg",
    additionalImages: [
      "Panadería y Dulcería/IMG-20250508-WA0019.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0019.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0019.jpg",
    ],
    category: "bakery",
    subcategory: "Muffin",
    allowBankTransfer: true,
  },
  {
    id: "muffin2",
    title: "Cake",
    title1: null,
    price: 3500,
    offerPrice: null,
    stock: 12,
    img: "Panadería y Dulcería/IMG-20250508-WA0018.jpg",
    additionalImages: [
      "Panadería y Dulcería/1.png",
      "Panadería y Dulcería/2.png",
      "Panadería y Dulcería/3.png",
      "Panadería y Dulcería/IMG-20250511-WA0009.jpg",
      "Panadería y Dulcería/IMG-20250511-WA0008.jpg",
      "Panadería y Dulcería/IMG-20250511-WA0007.jpg",
    ],
    category: "bakery",
    subcategory: "Muffin",
    allowBankTransfer: true,
  },
  {
    id: "muffin3",
    title: "MiniCake ",
    title1: null,
    price: 1800,
    offerPrice: null,
    stock: 12,
    img: "Panadería y Dulcería/IMG-20250508-WA0017.jpg",
    additionalImages: [
      "Panadería y Dulcería/IMG-20250508-WA0017.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0017.jpg",
      "Panadería y Dulcería/IMG-20250508-WA0017.jpg",
    ],
    category: "bakery",
    subcategory: "Muffin",
    allowBankTransfer: true,
  },
  {
    id: "coffe",
    title: "Fresh Grinded Frappé coffee",
    title1: null,
    price: 1.5,
    offerPrice: null,
    stock: 12,
    img: "coffe.jpg",
    additionalImages: ["coffe-beans.jpg", "coffe-ground.jpg", "coffe-brewing.jpg"],
    category: "drink",
    subcategory: "Coffee",
    allowBankTransfer: true,
  },
  {
    id: "coffe2",
    title: "Caffee Nero Mocha Late",
    title1: null,
    price: 1.8,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    additionalImages: ["coffe2-beans.jpg", "coffe2-brewing.jpg", "coffe2-cup.jpg"],
    category: "drink",
    subcategory: "Coffee",
    allowBankTransfer: true,
  },
  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    title1: null,
    price: 2.2,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    additionalImages: ["coffe3-jar.jpg", "coffe3-spoon.jpg", "coffe3-cup.jpg"],
    category: "drink",
    subcategory: "Coffee",
    allowBankTransfer: true,
  },
  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    title1: null,
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    additionalImages: ["coffe4-package.jpg", "coffe4-beans.jpg", "coffe4-brewing.jpg"],
    category: "drink",
    subcategory: "Coffee",
    allowBankTransfer: true,
  },
  {
    id: "coffe444",
    title: "Zapato de mujer (Fashion)",
    title1: "Talla: 40",
    price: 3500,
    offerPrice: null,
    stock: 12,
    img: "Ropa_calzado_accesorios/zapatos/Zapato de mujer (Fashion).jpg",
    additionalImages: [
      "Ropa_calzado_accesorios/zapatos/Zapato de mujer (Fashion)-lateral.jpg",
      "Ropa_calzado_accesorios/zapatos/Zapato de mujer (Fashion)-suela.jpg",
      "Ropa_calzado_accesorios/zapatos/Zapato de mujer (Fashion)-trasera.jpg",
      "Ropa_calzado_accesorios/zapatos/Zapato de mujer (Fashion)-detalle.jpg",
    ],
    category: "Ropa_calzado_accesorios",
    subcategory: "Calzado",
    allowBankTransfer: true,
  },
  {
    id: "comp-mb-1",
    title: "ASUS ROG Strix B550-F Gaming Motherboard",
    title1: "AMD AM4 Socket, PCIe 4.0",
    price: 8500,
    offerPrice: 7999,
    stock: 5,
    img: "Components/motherboards/asus-rog-b550.jpg",
    additionalImages: [
      "Components/motherboards/asus-rog-b550-box.jpg",
      "Components/motherboards/asus-rog-b550-ports.jpg",
      "Components/motherboards/asus-rog-b550-installed.jpg",
    ],
    category: "Components",
    subcategory: "Placas base",
    allowBankTransfer: true,
  },
  {
    id: "comp-gpu-1",
    title: "NVIDIA GeForce RTX 3060 Ti Graphics Card",
    title1: "8GB GDDR6, Ray Tracing",
    price: 15000,
    offerPrice: null,
    stock: 3,
    img: "Components/graphics-cards/rtx-3060ti.jpg",
    additionalImages: [
      "Components/graphics-cards/rtx-3060ti-box.jpg",
      "Components/graphics-cards/rtx-3060ti-ports.jpg",
      "Components/graphics-cards/rtx-3060ti-installed.jpg",
    ],
    category: "Components",
    subcategory: "Tarjetas gráficas",
    allowBankTransfer: true,
  },
  {
    id: "comp-cpu-1",
    title: "AMD Ryzen 7 5800X Processor",
    title1: "8 Cores, 16 Threads, Up to 4.7GHz",
    price: 12500,
    offerPrice: 11800,
    stock: 7,
    img: "Components/processors/ryzen-7-5800x.jpg",
    additionalImages: [
      "Components/processors/ryzen-7-5800x-box.jpg",
      "Components/processors/ryzen-7-5800x-bottom.jpg",
      "Components/processors/ryzen-7-5800x-installed.jpg",
    ],
    category: "Components",
    subcategory: "Procesadores",
    allowBankTransfer: true,
  },
  {
    id: "comp-hdd-1",
    title: "Samsung 970 EVO Plus 1TB NVMe SSD",
    title1: "M.2 PCIe Gen 3.0, Up to 3,500 MB/s",
    price: 4500,
    offerPrice: null,
    stock: 10,
    img: "Components/hard-drives/samsung-970-evo.jpg",
    additionalImages: [
      "Components/hard-drives/samsung-970-evo-box.jpg",
      "Components/hard-drives/samsung-970-evo-installed.jpg",
      "Components/hard-drives/samsung-970-evo-benchmark.jpg",
    ],
    category: "Components",
    subcategory: "Discos duros",
    allowBankTransfer: true,
  },
  {
    id: "comp-fan-1",
    title: "Tempest Fan 120mm PWM Ventilador",
    title1: "Suplementario Negro",
    price: 4500,
    offerPrice: null,
    stock: 10,
    img: "Componentes/Refrigeración/1787-corsair-rs120-ventilador-suplementario-pwm-120mm-negro.webp",
    additionalImages: [
      "Componentes/Refrigeración/tempest-fan-120mm-side.webp",
      "Componentes/Refrigeración/tempest-fan-120mm-installed.webp",
      "Componentes/Refrigeración/tempest-fan-120mm-rgb.webp",
    ],
    category: "Components",
    subcategory: "Refrigeración",
    allowBankTransfer: true,
  },
  {
    id: "comp-ram-1",
    title: "Corsair Vengeance RGB Pro 16GB RAM",
    title1: "2x8GB DDR4 3200MHz CL16",
    price: 3200,
    offerPrice: 2999,
    stock: 15,
    img: "Components/ram/corsair-vengeance.jpg",
    additionalImages: [
      "Components/ram/corsair-vengeance-box.jpg",
      "Components/ram/corsair-vengeance-rgb.jpg",
      "Components/ram/corsair-vengeance-installed.jpg",
    ],
    category: "Components",
    subcategory: "RAM",
    allowBankTransfer: true,
  },
  {
    id: "comp-psu-1",
    title: "EVGA SuperNOVA 750 G5 Power Supply",
    title1: "750W 80+ Gold Certified, Fully Modular",
    price: 4800,
    offerPrice: null,
    stock: 8,
    img: "Components/power-supplies/evga-supernova.jpg",
    additionalImages: [
      "Components/power-supplies/evga-supernova-box.jpg",
      "Components/power-supplies/evga-supernova-cables.jpg",
      "Components/power-supplies/evga-supernova-installed.jpg",
    ],
    category: "Components",
    subcategory: "Fuentes de alimentación",
    allowBankTransfer: true,
  },
  {
    id: "comp-other-1",
    title: "Noctua NH-D15 CPU Cooler",
    title1: "Dual Tower Design, 140mm Fans",
    price: 3600,
    offerPrice: 3299,
    stock: 6,
    img: "Components/other-components/noctua-nh-d15.jpg",
    additionalImages: [
      "Components/other-components/noctua-nh-d15-box.jpg",
      "Components/other-components/noctua-nh-d15-fans.jpg",
      "Components/other-components/noctua-nh-d15-installed.jpg",
    ],
    category: "Components",
    subcategory: "Otros componentes",
    allowBankTransfer: true,
  },



{
    id: "photography-other-1",
    title: "OM SYSTEM OLYMPUS VG-120",
    title1: "",
    price: 3000,
    offerPrice: null,
    stock: 1,
    img: "Fotografía y Accesorios/Cámaras de fotos/OM SYSTEM OLYMPUS VG-120.jpg",
    additionalImages: [
      "Fotografía y Accesorios/Cámaras de fotos/OM SYSTEM OLYMPUS VG-120-2.jpg",
      "Fotografía y Accesorios/Cámaras de fotos/OM SYSTEM OLYMPUS VG-120-3.jpg",
      "Fotografía y Accesorios/Cámaras de fotos/OM SYSTEM OLYMPUS VG-1201.jpg",
    ],
    category: "Photography",
    subcategory: "Cámaras de fotos",
    allowBankTransfer: true,
  },

{
    id: "photography-other-2",
    title: "Sony DCR-SX40 Handycam®",
    title1: "4GB flash memory/Memory Stick® camcorder (Silver)",
    price: 6000,
    offerPrice: null,
    stock: 1,
    img: "Fotografía y Accesorios/Cámaras de video/x158SX40-f.jpeg",
    additionalImages: [
      "Fotografía y Accesorios/Cámaras de video/h158SX40-b.jpeg",
      "Fotografía y Accesorios/Cámaras de video/x158SX40-i.jpeg",
      "Fotografía y Accesorios/Cámaras de video/x158SX40-w.jpeg",
    ],
    category: "Photography",
    subcategory: "Cámaras de vídeo",
    allowBankTransfer: true,
  },





]

export default products
